### ISSUE TITLE
Post messages 

### ISSUE THREAD

**Issue by dorian599** [absmach/magistrala#194]
**BUG REPORT**

1. What were you trying to achieve?
I'm trying to Publish Values via HTTP API with **curl**

2. What are the expected results?
The published value via API must be received for the clients subscribed to the channel

3. What are the received results?
After publish values via API, none of the subscribed clients receive the values

4. What are the steps to reproduce the issue?
**Subscribe a client via "mosquitto"**
`mosquitto_sub -h mainflux.server.com -p 1883 -v -u <client_id> -P <client_token> -t mainflux/channels/e2a7275d-e956-4d2f-adc5-50f943ae3b5f/messages/senml-json`

**Publish somethig via API**
`curl -k -s -S -i -X POST -H "Content-Type: application/senml+json" -H "Authorization: <client_token>" https://mainflux.server.com/channels/e2a7275d-e956-4d2f-adc5-50f943ae3b5f/messages -d '[{"n":"client001","u":"Cel","v":23.23}]'`

5. In what environment did you encounter the issue?
Running Mainflux on Debian 9 server and the "mosquitto" client is connected from another small Debian server

**Comment by drasko** [comment]
@dorian599 we are in the middle of adding `protobuf` support to MQTT broker. Will be finished tonight or tomorrow.

@nmarcetic is working on this one.

**Comment by drasko** [comment]
Btw - try using previous release: https://github.com/mainflux/mainflux/releases/tag/0.1.2 - it should work. Master is currently broken.

**Comment by mijicd** [comment]
Master is not broken. MQTT adapter is piece of software that is separately maintained. All of the elements present in `master` are stable.

I am closing this issue since it belongs to the MQTT adapter, not the core platform.

**Comment by drasko** [comment]
Should be fixed by https://github.com/mainflux/mqtt-adapter/pull/10 - @nmarcetic will confirm on https://github.com/mainflux/mainflux/issues/197

**Comment by dorian599** [comment]
I am trying to publish messages via API with this CURL command
`curl -k -s -S -i -X POST -H "Content-Type: application/senml+json" -H "Authorization: <client_token>" https://mainflux.server.com/channels/c7c6dfef-fe0f-44eb-b49c-95c154b77c1f/messages -d '[{"n":"rpi001","u":"Cel","v":23.23}]'`

I got an **200** OK HTTP code but the customers subscribed via mosquito still do not receive the messages

**Comment by mijicd** [comment]
@dorian599 Let me restate that the MQTT adapter is separately maintained. As part of the #159, the topics have been maintained which is not reflected in the MQTT.

@drasko and @nmarcetic will take a look at this
